# .streamlit/config.toml  # Archivo de configuración de tema para Streamlit.

[theme]  # Sección de tema de Streamlit.
base="light"  # Usa tema claro como base.
primaryColor="#0F0F0F"  # Negro corporativo para acentos (botones/links).
backgroundColor="#FFFFFF"  # Fondo general blanco.
secondaryBackgroundColor="#F7F7F7"  # Fondo para tarjetas/containers.
textColor="#111111"  # Texto principal casi negro.
font="sans serif"  # Fuente sans por defecto (combinaremos con CSS inyectado).

