# .streamlit/config.toml
# Tema base para TODA la app (colores por defecto). El CSS seguirá afinando el look.

[theme]
base = "light"                 # Modo claro como base
primaryColor = "#0F0F0F"       # Negro para botones/enlaces primarios (coincide con --primary)
backgroundColor = "#FFFFFF"    # Fondo general blanco (la imagen de fondo va por CSS)
secondaryBackgroundColor = "#FFFFFF"  # Fondos de contenedores/tarjetas (dejamos blanco para no pelear con el CSS)
textColor = "#111111"          # Texto principal casi negro
font = "sans serif"            # Tipografía base; cargamos Inter por CSS


